### ISSUE TITLE
DataPackagerPlugin implements IResourceUpload

### ISSUE THREAD

**Issue by florianm** [ckan/ckanext-datapackager#24]
Hi, I'm trying to install ckanext-datapackager. The ckan branch `datapackager` doesn't seem to be available any more, and the IResourceUpload plugin is not in the latest ckan master either.

Is there a currently working installation pathway for ckanext-datapackager? Or does it need to be refactored to use https://github.com/ckan/ckan/pull/1875?

**Comment by vitorbaptista** [comment]
@florianm This plugin was built to work on CKAN 2.2, and quite a bit have changed since then. I'm working on bringing it to CKAN 2.4, focusing first just on exporting and importing CKAN datasets to data packages. Later we might start moving the schema editing interface that was built here, but I'm not sure the when it'll be done.

If you'd like to follow the progress, check issue https://github.com/ckan/ckanext-datapackager/issues/25.
